version: "2"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5434:5432"

  web:
    build: .
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: "240"
